### ISSUE TITLE
size and controller String error

### ISSUE THREAD

**Issue by kasperkamperman** [evil-mad/stipplegen#1]
I use Processing 3.0b5 and ControlP5 2.2.5. 

The size() method doesn't support variables as input anymore. Solution for that is the hardcode the numbers: size(800, 710, JAVA2D);

Apart from that I get an error with ControlP5. 
The function "controller(String)" does not exist. 

For example with this line: `cp5.controller("SAVE_STIPPLES").setCaptionLabel("Save Stipple File (.SVG format)");`

I can't find a solution for that.

**Comment by oskay** [comment]
We have not tried under Processing 3.0 yet. Every new release breaks a few things-- we'll take a look.

**Comment by mzauliczny** [comment]
you need to replace every occurence of `cp5.controller()` to `cp5.getController()`, you also need to replace `cp5.controller("Stipples").value()` to `cp5.getController("Stipples").getValue()`
