### ISSUE TITLE
Controlling Stipple number – very difficult in lower ranges

### ISSUE THREAD

**Issue by simonhrogers** [evil-mad/stipplegen#14]
Hi there,

I wanted to play around with the lowest number of stipples possible, but can only access the following ranges at the bottom end of the scale as the app doesn’t give fine enough control / offer a way of inputting numbers manually. 

I can only access:

10, 76, 143, 209, 276, 343 etc.

Thank You,

Simon

**Comment by oskay** [comment]
Find where it says 

```
cp5.addSlider("sliderStipples", 10, 10000, maxParticles, 10, gui2ndRow, 150, 10)
    .setGroup(l3);
```

and change that minimum from 10 to (maybe) 1 and the upper lit to what you would like, maybe 100.
