### ISSUE TITLE
error

### ISSUE THREAD

**Issue by RickyBurton** [evil-mad/stipplegen#17]
Hello, I keep getting an error, I used this software months ago, and it worked fine, I reinstalled it, and nothing wants to work.

As for libraries, I got controlP5 from the processing website.
toxiclibs seem to be impossible to find.

Now I have the libraries. I get this issue. Any guidance?
![Screenshot 2022-05-14 132430](https://user-images.githubusercontent.com/33911127/168425716-09354821-98d0-4c37-b22a-918f2148e664.png)

**Comment by oskay** [comment]
Which version of Processing?

**Comment by RickyBurton** [comment]
Solved I redownloaded the code from the GitHub and was fine must have been an issue on the initial download.

**Comment by oskay** [comment]
This same issue was apparently reported several years ago ( https://github.com/evil-mad/stipplegen/issues/1 ) , and we did post a fix for it. The line that you're getting the error was changed (back in 2015).

Please try the current version, available from this repository.
