### ISSUE TITLE
Break the stipple count barirer and voronoi net svg export

### ISSUE THREAD

**Issue by Tungee** [evil-mad/stipplegen#5]
Is it possible to uprise the max stipple count of 10000 to much more for example 100K or more?! In a lot of cases much more are needed.

It would be also nice, if we could export the voronoi net also beside the tsp and stipple svg export.

I played the whole night with it and it makes so much fun :)

Best regards! Tungee

**Comment by oskay** [comment]
These are completely separate issue reports. Please open separate reports for unrelated feature requests.

**Comment by Tungee** [comment]
Hi Oskay,
should i open 2 new issues?
One for the max stipple count and one for the  Voronoi export?

Best regards

**Comment by oskay** [comment]
That is your call to make, not mine.
