### ISSUE TITLE
Request- rise up maximum stipple count

### ISSUE THREAD

**Issue by Tungee** [evil-mad/stipplegen#6]
I have a reqeust regarding the max stipple count of 10000.
I would propagate a much higher max. stipple count, 100000 perhaps?!
Best Regards

**Comment by oskay** [comment]
If you press the "x" key on your keyboard, it will change the max to 50,000. _However_, this will also slow down the performance when you operate with higher stipple count. At above 50,000, it's not really usable.

**Comment by Tungee** [comment]
Awesome, Oskay! I would it let it run overnight!! So nice!

2016-12-12 19:39 GMT+01:00 Windell Oskay <notifications@github.com>:

**Comment by Tungee** [comment]
Im reading the wiki more carefully now... the passage with the super secret
bonus trick ;)

2016-12-12 19:42 GMT+01:00 Hakan Tunc <tungee78@gmail.com>:
